name: Build Xash3D 0.21 OP4

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y ninja-build

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Make script executable
        run: chmod +x scripts/android-gms.sh

      - name: Run Android GMS script
        run: ./scripts/android-gms.sh -g gearbox

      - name: Check build directory
        run: ls -la build-android

      - name: Build APK
        run: |
          cd build-android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: xash3d-opfor-apk
          path: build-android/app/build/outputs/apk/release/*.apk
